### ISSUE TITLE
Errors not showing but Linting is working

### ISSUE THREAD

**Issue by dbarn** [SublimeLinter/SublimeLinter#332]
Hi,

I have two linters installed, JSLint and PHPLint.
If I open a javascript file the linter runs and I see the pop up warning if there are any errors. (I see the errors in the console too)

If I open a php file the linter runs but I dont see the pop up.
The console does show me the erros but I don't see anything else.

If I run the linter from the command line it runs:
**OUTPUT FROM TERMINAL:**

dave ~ $ phplint --print-path shortest --print-context --tab-size 4 --no-overall test.php 
BEGIN parsing of test.php
1:  <?php
2:  
3:  thisisan error;

```
thisisan error;
              \_ HERE
```

==== 3: ERROR: unknown constant thisisan

```
thisisan error;
              \_ HERE
```

==== 3: ERROR: missing statement terminator `;' or`?>'

```
thisisan error;
               \_ HERE
```

==== 3: ERROR: unknown constant error
4:  
5:  ?>
END parsing of test.php

**This is the output from my Sublime Console from startup:**

DPI scale: 1
startup, version: 3083 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/dave/.config/sublime-text-3/Packages
state path: /home/dave/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/dave/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.241897
startup time: 0.462924
first paint time: 0.498339
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/dave/.config/sublime-text-3/Packages/HTML/encode_html_entities.py", line 6, in <module>
    from htmlentitydefs import codepoint2name as cp2n
ImportError: No module named 'htmlentitydefs'
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Package Control: Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SideBarGit.SideBarAPI
reloading plugin SideBarGit.SideBarGit
reloading plugin SideBarGit.SideBarGitCommands
reloading plugin SublimeLinter-jshint.linter
SublimeLinter: jshint linter loaded 
reloading plugin SublimeLinter-phplint.linter
SublimeLinter: phplint linter loaded 
reloading plugin Alignment.Alignment
reloading plugin CodeFormatter.CodeFormatter
CodeFormatter: formatting python files on ST3 not supported.
reloading plugin Emmet.emmet-plugin
reloading plugin EncodingHelper.EncodingHelper
reloading plugin FileDiffs.file_diffs
reloading plugin Javascript Beautify.jsbeautify
reloading plugin LESS.less_completions
reloading plugin Laravel 5 Artisan.Laravel 5 Artisan
reloading plugin Less2Css.less2css
reloading plugin Less2Css.lesscompiler
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeOnSaveBuild.SublimeOnSaveBuild
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /tmp/SublimeLinter3-dave 
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/usr/lib/jvm/java-7-openjdk-amd64/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/home/dave/Development/android-sdk-linux/tools
/home/dave/Development/android-sdk-linux/platform-tools
/home/dave/.composer/vendor/bin

SublimeLinter: phplint version query: /usr/bin/phplint --version 
SublimeLinter: phplint version: 2.1 
SublimeLinter: phplint: (>= 1.1) satisfied by 2.1 
SublimeLinter: phplint activated: /usr/bin/phplint 
SublimeLinter: jshint version query: /usr/local/bin/jshint --version 
SublimeLinter: jshint version: 2.8.0 
SublimeLinter: jshint: (>= 2.5.0) satisfied by 2.8.0 
SublimeLinter: jshint activated: /usr/local/bin/jshint 
CodeFormatter: Plugin Initialized
Emmet: No need to update PyV8
SublimeLinter: jshint: test.php ['/usr/local/bin/jshint', '--verbose', '--filename', '@', '--extract=always', '-'] 
SublimeLinter: phplint: test.php ['/usr/bin/phplint', '--print-path', 'shortest', '--print-context', '--tab-size', '4', '--no-overall'] 
SublimeLinter: phplint output:
BEGIN parsing of /tmp/SublimeLinter3-dave/test.php
1:  <?php
2:  
3:  thisisan error;

```
thisisan error;
              \_ HERE
```

==== 3: ERROR: unknown constant thisisan

```
thisisan error;
              \_ HERE
```

==== 3: ERROR: missing statement terminator `;' or`?>'

```
thisisan error;
               \_ HERE
```

==== 3: ERROR: unknown constant error
4:  
5:  ?>
END parsing of /tmp/SublimeLinter3-dave/test.php 

This is my SublimeLinter.sublime-settings FILE:

{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Circle/Circle.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "jshint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "phplint": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "fill",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": true,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}

Any ideas would be great!!

Thanks
Dave

**Comment by RiaanBurger** [comment]
Experiencing something similar. Clear errors when run from the command line, no errors reported in the console in debug mode and no linting errors reported.

**Comment by RiaanBurger** [comment]
I removed all the SublimeLinter packages and reinstalled them. Got an error this time that phpcs could not be found (and JSON was working). Added paths to my user configuration for SublimeLinter (Preferences -> Package Settings -> SublimeLinter -> Settings - User).

Find the location of your executables with ```which phpcs```.

This is the bit I added:

```json
        "paths": {
            "linux": [
                "/home/riaan/.composer/vendor/bin/",
                "/usr/bin/"
            ],
            "osx": [],
            "windows": []
        },
```

Works here now.

**Comment by dbarn** [comment]
Thanks for this. I swtiched to using phpcs and removed the phplint plugin from the sublimelinter config.
All good now.

**Comment by jimba** [comment]
@RiaanBurger Adding "~/.composer/vendor/bin" to the "osx" identifier helped me. Thanks a bunch!

**Comment by whw** [comment]
I'm running into a similar issue. 

PROBLEM: Lint errors are not being highlighted

DESCRIPTION: When linting a bad python file, I see the lint error occurring both on the command line and in the console, but no highlighting is occurring in the file.

Context:
ST v3.0, Build 3143
OS: 10.12.6
Python: 3.6
I've installed flake8 via pip inside of a conda environment.
I've installed both SublimeLinter and SublimeLinter-flake8 plugin via Package Control

Console output:
```
SublimeLinter: find_posix_python: python3 => /Users/wwilliams/miniconda3/bin/python3 
SublimeLinter: find_python: system python = /Users/wwilliams/miniconda3/bin/python3 
SublimeLinter: find_python: available version = {'major': 3, 'minor': 6} 
SublimeLinter: find_python: <= ('/Users/wwilliams/miniconda3/bin/python3', None, 3, 6) 
SublimeLinter: sys.path for /Users/wwilliams/miniconda3/bin/python3:
/Users/wwilliams/miniconda3/lib/python36.zip
/Users/wwilliams/miniconda3/lib/python3.6
/Users/wwilliams/miniconda3/lib/python3.6/lib-dynload
/Users/wwilliams/miniconda3/lib/python3.6/site-packages
/Users/wwilliams/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg
 
SublimeLinter: flake8 version query: /Users/wwilliams/miniconda3/bin/flake8 --version 
SublimeLinter: flake8 version: 3.4.1 
SublimeLinter: flake8: (>= 2.2.2) satisfied by 3.4.1 
SublimeLinter: flake8 activated: /Users/wwilliams/miniconda3/bin/flake8 
SublimeLinter: flake8: test_failed_charge.py ['/Users/wwilliams/miniconda3/bin/flake8', '--max-complexity=-1', '--jobs=1', '-'] 
SublimeLinter: flake8 output:
stdin:4: [F401] 'datetime' imported but unused 
```

Command-line output:
```
> flake8 test_failed_charge.py                                                                                                                
test_failed_charge.py:4: [F401] 'datetime' imported but unused
```

SublimeLinter.sublime-settings

```
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "load/save",
        "linters": {
            "flake8": {
                "@disable": false,
                "args": [],
                "builtins": "",
                "excludes": [],
                "executable": "",
                "ignore": "",
                "jobs": "1",
                "max-complexity": -1,
                "max-line-length": null,
                "select": "",
                "show-code": false
            }
        },
        "mark_style": "solid underline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [
                "~/miniconda3/bin"
            ],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": true,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "tooltip_fontsize": "1rem",
        "tooltip_theme": "Packages/SublimeLinter/tooltip-themes/Default/Default.tooltip-theme",
        "tooltip_theme_excludes": [],
        "tooltips": false,
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by kaste** [comment]
@whw You highjacked this issue 😄 and we can't replicate it. We're also already 300 commits away since you reported, and in SL4 it will be a bit easier to debug. So I'm closing.

The original issue has been resolved.

**Comment by whw** [comment]
@kaste apologies! Had no intention of hijacking this.

I got SL4 beta installed (along with the corresponding SublimeLinter-flake8 package) - and unfortunately I'm still having this issue.

Would it be better to track this in a completely separate issue?

**Comment by whw** [comment]
cc @braver

**Comment by FichteFoll** [comment]
@whw yes, I suggest creating a new issue with new console output and your new settings file.

**Comment by whw** [comment]
@FichteFoll can do - would y'all prefer it here or do you think it would be better in the `SublimeLinter-flake8` repo?

**Comment by FichteFoll** [comment]
Since it is likely to involve the current beta, I suggest posting it here.

**Comment by FichteFoll** [comment]
@whw also, make sure you are installing pre-releases for flake8 as well, since the current stable release of that isn't compatible with SL4.

**Comment by whw** [comment]
@FichteFoll opened here: https://github.com/SublimeLinter/SublimeLinter/issues/833
