### ISSUE TITLE
"Sublimelinter could not determine your shell path"

### ISSUE THREAD

**Issue by brownieboy** [SublimeLinter/SublimeLinter#725]
I'm getting the error "Sublimelinter could not determine your shell path" every time I open SublimeText.  This is on OS X Sierra

The Sublime console shows the following:
> SublimeLinter: eslint output:
> env: node: No such file or directory

So it looks like it can't find Node?

Node and Python are both installed via Brew on this Mac, and they are locatable at the command line (i.e. they _don't_ return "command not found" errors when I type the respective commands in a terminal.)

Issuing a `which node` command in the terminal returns /usr/local/bin/node, which appears to be symlink to where Node is actually installed, somewhere under /usr/local/Cellar.  Note: this is Node 6 rather than the latest one, so shows as `node@6` when I run a `brew list` command.  However, I did run the `brew link node@6 --force` command after installiing Node, and that reported that it set up "7 symlinks" somewhere or other.

**Comment by kaste** [comment]
Similiar https://github.com/SublimeLinter/SublimeLinter3/pull/670

Try to comment https://github.com/SublimeLinter/SublimeLinter3/blob/1e17d1a3253e5e764cc6d0e7ded0cdbea5a70a2b/lint/util.py#L389-L407 

and/or `print(path)` 

https://github.com/SublimeLinter/SublimeLinter3/blob/1e17d1a3253e5e764cc6d0e7ded0cdbea5a70a2b/lint/util.py#L363-364

**Comment by brownieboy** [comment]
Thank you for your response, @kaste.  I followed your instructions and I now have linting working in Sublime!!!

The `util.py` file that I needed to edit was in the `/Packages/SublimeLinter/lint` sub-folder of my Sublime installed folder.  And the lines to comment out started at line 533.

Here's what I commented out
```
   if 'SHELL' in env:
        shell_path = env['SHELL']
        shell = os.path.basename(shell_path)

        # We have to delimit the PATH output with markers because
        # text might be output during shell startup.
        # if shell in ('bash', 'zsh'):
        #     return extract_path(
        #         (shell_path, '-l', '-c', 'echo "__SUBL_PATH__${PATH}__SUBL_PATH__"')
        #     )
        # elif shell == 'fish':
        #     return extract_path(
        #         (shell_path, '-l', '-c', 'echo "__SUBL_PATH__"; for p in $PATH; echo $p; end; echo "__SUBL_PATH__"'),
        #         '\n'
        #     )
        # else:
        #     from . import persist
        #     persist.printf('Using an unsupported shell:', shell)
```

And bingo!

I've never edited a Python file _ever_ before today.  So, what is it that I just did?

**Comment by kaste** [comment]
Haha. It would be really helpful, if you could undo what you did and print(path) at line 364 as mentioned in my first comment.

You could then see what it prints in the console view and post it.

After that, just redo the fix so that you have a working version again.

**Comment by kaste** [comment]
Oh, I see you have different line numbers. It's in the function right above.

**Comment by brownieboy** [comment]
Done.  Your line 364 was line 576 in my util.py file.

Here's what it outputted:
`/Applications/Sublime Text.app/Contents/MacOS`

**Comment by kaste** [comment]
Very nice. 

Actually that's the output I expected intuitively.

Hang on, we need to think this through. 🤔

**Comment by brownieboy** [comment]
Okay, and thanks again.

If you want me to completely remove Sublime and then reinstall from scratch, I'm happy to try that.

**Comment by FichteFoll** [comment]
What *is* your `$SHELL` btw?

**Comment by brownieboy** [comment]
echo $SHELL = "/bin/bash"

**Comment by kaste** [comment]
@braver has committed a "fix" for the next SublimeLinter version. So, this could be closed. ❓ 

@brownieboy For the current version, you should just keep the fix you applied manually.

**Comment by braver** [comment]
@brownieboy we have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by braver** [comment]
Should be fixed in #786

**Comment by KempfCreative** [comment]
Sorry to resurrect a closed bug, but I have been encountering this issue ( or a similar one ), and I wanted to add my logging output to this. If you would rather have me open a new issue, that is totally fine.

`print( path )` in `def extract_path` is `['']`

with debug mode on, the log output after SublimeLinter is reloaded:
```
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/sn/r3jz2xq5153dqfy4fzm_7g100000gp/T/SublimeLinter3-<USER> 
no output from shell "/bin/bash"
Emmet: No need to update PyV8
SublimeLinter: user shell: /bin/bash 
GitGutter: git not found or working!
SublimeLinter: shell timed out after 30 seconds, executing ('/bin/bash', '-l', '-c', 'echo "__SUBL_PATH__${PATH}__SUBL_PATH__"') 
['']
SublimeLinter: Could not parse shell PATH output:
<empty> 
error: SublimeLinter could not determine your shell PATH. It is unlikely that any linters will work. 

Please see the troubleshooting guide for info on how to debug PATH problems.
SublimeLinter: computed PATH using /bin/bash:
/Users/<USER>/.nvm/versions/node/v8.9.3/bin/eslint

 
SublimeLinter: eslint: loadEntry.js ['/Users/<USER>/<PATH_TO_PROJECT>/node_modules/.bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
env: node: No such file or directory 
SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fad16d16fc0> 
```

Commenting out the lines listed by @kaste 'fixed' the issue I was having.

**Comment by FichteFoll** [comment]
>SublimeLinter: No match for <_sre.SRE_Pattern object at 0x7fad16d16fc0> 

I'm pretty sure I fixed this weeks ago, unless a recent change made it regress. If you aren't running it already, you should try the SL4 pre-releases as instructed in the readme.

**Comment by KempfCreative** [comment]
@FichteFoll I am not using the SL4 pre-releases, as my mental capacity to work on any more linter configuration is spent for the day. I'll try it tomorrow and let you know the results.

**Comment by braver** [comment]
I do need to release a new beta though, perhaps it hasn’t rolled out yet?

**Comment by kaste** [comment]
This has been fixed for SL4. A fix for SL3 was and is out of scope.

@FichteFoll Fixed for SL4 as well

**Comment by optyler** [comment]
Hi guys, I'm already on version 4 of SL but I still have the issue : 

```
SublimeLinter: SublimeLinter.sublime-package:63: version: 4.0.6
SublimeLinter: SublimeLinter.sublime-package:256: detected syntax: javascript
SublimeLinter: #1 SublimeLinter.sublime-package:782: 'eslint' is linting 'conversion.js'
SublimeLinter: #1 SublimeLinter.sublime-package:1186: eslint: conversion.js ['/Users/pferreira/Documents/workspace/v2v3/geronimo-front/node_modules/.bin/eslint', '--format', 'json', '--stdin', '--stdin-filename', '/Users/pferreira/Documents/workspace/v2v3/geronimo-front/utils/conversion.js']
SublimeLinter: #1 SublimeLinter.sublime-package:1189: eslint: cwd: /Users/pferreira/Documents/workspace/v2v3/geronimo-front
SublimeLinter: #1 SublimeLinter.sublime-package:809: eslint output:
    env: node: No such file or directory
SublimeLinter: #1 SublimeLinter-eslint.sublime-package:54: ERROR: env: node: No such file or directory
```

For information, my `eslint` binary is in `${project}/node_modules/.bin/`

**Comment by feus4177** [comment]
I think I am also seeing this issue:
```
Package Control: Skipping automatic upgrade, last run at 2018-03-13 13:28:30, next run at 2018-03-13 14:28:30 or after
SublimeLinter: ERROR: env: node: No such file or directory
```
SublimeText 3
SublimeLinter: v4.0.6
OSX El Capitan: 10.11.6

**Comment by kaste** [comment]
We have a new PR at https://github.com/SublimeLinter/SublimeLinter/pull/1266 to fix this issue. Please check it!

**Comment by broox** [comment]
#1266 still fails to load the path for me ☹️

**Comment by exophunk** [comment]
Still same for me:

MacOS: 10.13.3
Sublime Text 3.0 (3143)


```
SublimeLinter: #1 eslint app.js ERROR:
======================================

env: node: No such file or directory
```

I use node via nvm but set the path in SublimeLinter settings:

```
// SublimeLinter Settings - User
{
	"paths": {
        "osx": [
        	"/Users/exophunk/.nvm/versions/node/v9.5.0/bin"
        ],
    },
}
```

**Comment by kaste** [comment]
I think the patch is in master, so it should be in the next version.
